### ISSUE TITLE
stub run fails with nextflow v24

### ISSUE THREAD

**Issue by samarth8392** [CCBR/LOGAN#70]
### Description of the bug

Dryrun failed with the following error:
```
ERROR ~ Error executing process > 'ALIGN:matchbed (1)'

Caused by:
  Cannot invoke method clone() on null object
```

### Command used and terminal output

```console
nextflow run /data/CCBR/projects/techDev/LOGAN/main.nf \
--mode local -profile ci_stub \
--genome hg38 \
--sample_sheet /data/CCBR/projects/techDev/logan_pairs.txt \
--outdir /data/CCBR/projects/techDev/runs/logan_test \
--fastq_file_input /data/CCBR/projects/techDev/logan_fastq_input.txt \
--vc --sv --cnv
```

### Relevant files

[nextflow.log](https://github.com/user-attachments/files/18576551/nextflow.log)

**Comment by dnousome** [comment]
Believe this is an issue with nextflow nextflow-io/nextflow#5456 . Bug should be fixed in their latest edge release

**Comment by samarth8392** [comment]
reverting the nextflow to previous version `nextflow/24.04.4` worked.

**Comment by samarth8392** [comment]
Hi @kelly-sovacool, This bug was reported in https://github.com/nextflow-io/nextflow/issues/5456 and was fixed in next nextflow update. The latest nextflow module is `nextflow/25.04.2` but ccbrpipeliner/8 is still using nextflow/24.10.3 (the buggy version). I am still getting the same error when i do stub run.
Can we bump up the nextflow version fo ccbrpipeliner 8?

```
ERROR ~ Error executing process > 'ALIGN:matchbed (1)'

Caused by:
  Cannot invoke method clone() on null object
```

**Comment by kelly-sovacool** [comment]
@samarth8392 the nextflow module can actually be controlled at the pipeline level. We'll just need to modify `src/__main__.py`. See the equivalent line in champagne here: https://github.com/CCBR/CHAMPAGNE/blob/3e82659637baffb7e5efddde312ea7bd922507f2/src/__main__.py#L148
